### ISSUE TITLE
Readin.c error

### ISSUE THREAD

**Issue by jakemco** [sharpee/mid#1]
The affected code starts on line 19 of the file readin.c

Incorrect: Github's readin.c > Line 19

```
if(x0 < 1 || x0 > Nh)
  myerror("x offset should be between 1 and Nh.");
if(y0 < 1 || y0 > Nh)
  myerror("y offset should be between 1 and Nv.");
```

Correct: readin.c

```
if(x0 < 1 || x0 > dimx-Nh+1)
  myerror("x offset should be between 1 and 1+dimx-Nh.");
if(y0 < 1 || y0 > dimy-Nv+1)
  myerror("y offset should be between 1 and 1+dimy-Nv.");
```

**Comment by chrishiestand** [comment]
Jake, if you're new to using git it would be good practice for you, and Tatyana, to fork this repository, fix the bug and send a pull request to her.

**Comment by chrishiestand** [comment]
Let me know if you'd like any assistance.

**Comment by jakemco** [comment]
Fork'd and Pull Request'd
